requires = ["setuptools"]
build-backend = "setuptools.build_meta"

name = "hockey_stats_project"
version = "0.1.0"
dependencies = [
    "lxml",
    "numpy",
    "pandas",
    "sqlalchemy",
    "python-dotenv",
    "dagster",
    "dagster-cloud",
    "dagster-webserver"
]